const CONFIG = {
  introTitle: 'Vợ ơiiiiii!',
  introDesc: `Anh có điều này muốn hỏi, vợ nhớ phải trả lời thật lòng nhaa`,
  btnIntro: 'Dạaaa ^0^',
  title: 'Vợ có yêu chồng không nhòoo ._.',
  desc: 'Có rất nhiều cách để hạnh phúc nhưng nhanh nhất chính là nhìn thấy vợ. ',
  btnYes: 'Em có yêu chồnggg <3',
  btnNo: 'Không nha chồng, ghét :) ',
  question: 'Vợ yêu anh ở điểm nào zợ ??',
  btnReply: 'Gửi cho anh <3',
  reply: 'Anh đẹp trai này, thương em này, lại còn ngoan nữa  <33333333',
  mess: ' Yêu Em nhiều nhiều 😘😘',
  messDesc: 'Nhắn tin cho Anh luôn nhó Vợ iu.',
  btnAccept: 'Okiiiii lun <3',
  messLink: '',
};
